version: '3.8'

services:

    unity:
        environment:
          - PORT=${UNITY_PORT}
          - UNITY_API_BASE_URI=${UNITY_API_BASE_URI}
          - UNITY_BASE_URI=${UNITY_BASE_URI}
          - UNITY_DEBUG=${UNITY_DEBUG}
          - USE_HTTPS=${USE_HTTPS}
          - STATUS_SITE_URL=${STATUS_SITE_URL}
          - SITE_TITLE=${SITE_TITLE}
          - SITE_DESCRIPTION_META=${SITE_DESCRIPTION_META}
          - SITE_DESCRIPTION=${SITE_DESCRIPTION}
          - SITE_HERO_IMAGE=${SITE_HERO_IMAGE}
        image: 140023379914.dkr.ecr.us-east-2.amazonaws.com/unity:${UNITY_VER}
        depends_on:
          - arc3-api
        container_name: unity
        restart: on-failure
        ports:
          - 3040:${UNITY_PORT}

    arc3:
        environment:
          - MONGODB_URI=${MONGODB_URI}
          - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
          - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
          - GUILD_ID=${GUILD_ID}
          - TOKEN=${TOKEN}
        image: 140023379914.dkr.ecr.us-east-2.amazonaws.com/arc3:${ARC3_VER}
        container_name: arc3
        restart: on-failure

    arc3-api:
        environment:
          - MONGODB_URI=${MONGODB_URI}
          - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
          - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
          - CLIENT_REDIRECT_URI=${CLIENT_REDIRECT_URI}
          - DIRECT_URL=${DIRECT_URL}
          - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
          - FULLCHAIN=${FULLCHAIN}
          - HOSTED_URL=${HOSTED_URL}
          - JWT_SECRET=${JWT_SECRET}
          - PORT=${API_PORT}
          - PRIVKEY=${PRIVKEY}
          - TOKEN=${TOKEN}
        image: 140023379914.dkr.ecr.us-east-2.amazonaws.com/arc3-api:${ARC3_API_VER}
        container_name: arc3-api
        restart: on-failure
        ports:
          - 3060:${API_PORT}

    mongo:
        image: mongo:7.0
        env_file:
          - .env
        container_name: mongo
        restart: always
        environment:
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
          - mongo_data:/data/db
          - mongo_config:/data/configdb
          - ./keys/mongo.keyfile:/data/mongo.keyfile
        ports:
          - 27018:27017

    mongo_admin_ui:
        image: mongo-express
        env_file:
            - .env
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - ME_CONFIG_MONGODB_SERVER=mongo
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PWRD}
        container_name: mongo_admin_ui
        ports:
            - 8081:8081

networks:
  common-net: {}

volumes:
  mongo_data:
  mongo_config:
  kuma_data:
