name: ssh-deploy-prod
on: 
  push:
    branches:
      - live
      
permissions:
  contents: read

jobs:
  ssh-deploy-prod:
    runs-on: ubuntu-latest
    environment: LIVE
    steps:
      - name: ssh-deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: echo ${{ vars.ENV }} >> github
