name: ssh-deploy
on: 
  pull_request:
  push:
    branches:
      - main
      
permissions:
  contents: read

jobs:

  ssh-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh-deploy
        uses: invi5H/ssh-action@v1.0.0
        with:
          # A unique name for the server
          NAME: stage-server
          # The SSH username
          SSH_USER: ${{ secrets.SSH_USER }}
          # The hostname or the IP address
          SSH_HOST:  ${{ secrets.SSH_HOST }}
          # The SSH port
          SSH_PORT:  ${{ secrets.SSH_PORT }}
          # The full string SSH key
          SSH_KEY:  ${{ secrets.SSH_KEY }}
