name: ssh-deploy
on: 
  push:
    branches:
      - main
      
permissions:
  contents: read

jobs:
  ssh-deploy-stg:
    runs-on: ubuntu-latest
    environment: STAGE
    steps:
      - name: ssh-deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: cd ${{ vars.ENV }} && echo ${{ secrets.SSH_PASSWORD}} | sudo -S ./deploy.sh
